import React from 'react';
import Navbar from '../../components/Navbar/Navbar';
import Footer from '../../components/Footer/Footer';
import Styles from './TermsAndConditions.module.css';
import { motion } from 'framer-motion';
import type { Variants } from 'framer-motion';


const containerVariants: Variants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      when: "beforeChildren",
      staggerChildren: 0.1,
      delayChildren: 0.2
    }
  }
};


const fadeUpItem: Variants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      ease: [0.16, 0.77, 0.47, 0.97],
      duration: 0.6
    }
  }
};


const Disclaimer: React.FC = () => {
  return (
    <div className={Styles.termsPageContainer}>
      <div className={Styles.navbarContainer}><Navbar /></div>
      <main className={Styles.contentWrapper}>
        <motion.section 
          className={Styles.termsSection}
          initial="hidden"
          animate="visible"
          variants={containerVariants}
        >
          <motion.div className={Styles.headingContainer} variants={fadeUpItem}>
            <h1 className={Styles.mainHeading}>Important Disclaimer</h1>
            <p className={Styles.subHeading}>
              Last updated: September 2025
            </p>
          </motion.div>
          
          <motion.div className={Styles.termsContentContainer} variants={fadeUpItem}>
            <div className={Styles.termsContent}>
              <section className={Styles.section}>
                <h2 className={Styles.sectionHeading}>Trading Journal and Analysis Tool Only</h2>
                <p className={Styles.sectionText}>
                  TradeJournalAI is exclusively a data logging and analysis platform for tracking your trading performance. We provide tools for manually entering trade data and generating performance analytics, charts, and reports based on your entries.
                </p>
                <p className={Styles.sectionText}>
                  Our platform does not provide trading advice, investment recommendations, buy/sell signals, or financial consulting services of any kind.
                </p>
              </section>


              <section className={Styles.section}>
                <h2 className={Styles.sectionHeading}>No Financial or Investment Advice</h2>
                <p className={Styles.sectionText}>
                  TradeJournalAI does not provide personalized investment advice, trading strategies, or market predictions. Our analysis features (performance charts, risk analysis, psychology tracking) are based solely on data you manually enter.
                </p>
                <p className={Styles.sectionText}>
                  All trading decisions remain entirely your responsibility. We strongly recommend consulting qualified financial advisors before making any investment decisions.
                </p>
              </section>


              <section className={Styles.section}>
                <h2 className={Styles.sectionHeading}>User Input Dependency</h2>
                <p className={Styles.sectionText}>
                  All analysis, charts, performance metrics, and reports generated by TradeJournalAI are based entirely on trade data that you manually enter through our forms. The accuracy of our analysis depends completely on the accuracy of your data input.
                </p>
                <p className={Styles.sectionText}>
                  We do not verify, validate, or guarantee the accuracy of user-entered data. Incorrect or incomplete data entry will result in inaccurate analysis and reporting.
                </p>
              </section>


              <section className={Styles.section}>
                <h2 className={Styles.sectionHeading}>Market Risk Warning</h2>
                <p className={Styles.sectionText}>
                  Trading in financial markets involves substantial risk of loss. Past performance tracked in our journal does not predict future results. Market conditions change constantly, and historical patterns may not indicate future outcomes.
                </p>
                <p className={Styles.sectionText}>
                  You could lose some or all of your invested capital. Our platform is for tracking and learning purposes only - not for making trading decisions.
                </p>
              </section>


              <section className={Styles.section}>
                <h2 className={Styles.sectionHeading}>Platform Limitations</h2>
                <p className={Styles.sectionText}>
                  TradeJournalAI requires users to manually enter all trade data through our forms. Our dashboard will remain empty until you input your trading information. We do not automatically import trades or connect to brokerage accounts (though this may be available in the future).
                </p>
                <p className={Styles.sectionText}>
                  Our analysis algorithms and calculations may contain errors or limitations. Users should independently verify all metrics and not rely solely on our platform for performance evaluation.
                </p>
              </section>


              <section className={Styles.section}>
                <h2 className={Styles.sectionHeading}>Subscription and Access</h2>
                <p className={Styles.sectionText}>
                  Our ₹99 Pro subscription provides access to logging tools and analysis features but does not guarantee improved trading performance, profits, or any specific outcomes.
                </p>
                <p className={Styles.sectionText}>
                  The 24-hour free trial allows you to evaluate our platform before purchasing. We encourage thorough testing during this period.
                </p>
              </section>


              <section className={Styles.section}>
                <h2 className={Styles.sectionHeading}>Future Features Disclaimer</h2>
                <p className={Styles.sectionText}>
                  We may introduce broker API integrations and additional features in the future. Such features will be optional and may require separate terms or additional fees.
                </p>
                <p className={Styles.sectionText}>
                  Current subscribers are not guaranteed access to future features without additional payment or agreement to new terms.
                </p>
              </section>


              <section className={Styles.section}>
                <h2 className={Styles.sectionHeading}>Limitation of Liability</h2>
                <p className={Styles.sectionText}>
                  TradeJournalAI and its operators are not liable for any trading losses, missed opportunities, data entry errors, or other consequences arising from platform usage.
                </p>
                <p className={Styles.sectionText}>
                  Users acknowledge they use our platform for logging and analysis purposes only, at their own risk, and are solely responsible for all trading decisions.
                </p>
              </section>


              <section className={Styles.section}>
                <h2 className={Styles.sectionHeading}>Contact Information</h2>
                <p className={Styles.sectionText}>
                  For questions about this disclaimer or our services:
                </p>
                <address className={Styles.contactInfo}>
                  Email: tradejournalai@gmail.com<br />
                  Phone: +91 9999999999<br />
                  Address: Bengaluru, Karnataka, India<br />
                  Website: https://tradejournalai.in
                </address>
                <p className={Styles.sectionText}>
                  This disclaimer may be updated periodically. Continued use constitutes acceptance of any changes.
                </p>
              </section>
            </div>
          </motion.div>
        </motion.section>
      </main>
      <div className={Styles.footerContainer}><Footer /></div>
    </div>
  );
};


export default Disclaimer;
